#!/usr/bin/env python3
"""Watch-then-avoid supervisor for the reasoning demo (option B).

Division of labour, per docs/code_vs_vla_responsibilities.md: this node
makes the DISCRETE safety decisions — when to hold, how long to watch,
when to commit to the pass, which lane — and the VLA does everything
continuous: the driving itself and the narration of every phase
(`/vla/reasoning`, generated by the same policy that drives).

State machine (arc distances along the obstacle's lane, signed — the
collector's battle-tested geometry from collect_corpus.py):

    approach --[fwd <= hold_at]--> hold(/vla/hold on)
    hold --[standstill >= watch_s]--> pass (hold off + lane-swapped sentence)
    pass --[obstacle behind >= clear_m]--> restore original sentence

Inputs: the obstacle registry (eval_out/demo/obstacles.json, same file
chat_gui's coordinate backstop reads), ego ground truth from the bridged
dynamic_pose topic, and the current instruction. Run alongside the demo
stack; it publishes only /vla/hold and /vla/instruction.

    python3 tools/demo/avoid_supervisor.py \
        [--hold-at 10.0] [--watch-s 2.5] [--clear-m 6.0]
"""

import argparse
import json
import math
import os
import sys
import time

import rclpy
from rclpy.node import Node
from rclpy.qos import (QoSDurabilityPolicy, QoSHistoryPolicy, QoSProfile,
                       QoSReliabilityPolicy)
from std_msgs.msg import String
from tf2_msgs.msg import TFMessage

WS = os.path.expanduser("~/ROS2_project/nav-vla")
REGISTRY = os.path.join(WS, "eval_out", "demo", "obstacles.json")
TRACK = os.path.join(WS, "src", "nav_vla_pkg", "config", "track_paths.json")

LANE_SENT = {"lane1": "inner", "lane2": "outer"}


class AvoidSupervisor(Node):
    def __init__(self, args):
        super().__init__("avoid_supervisor")
        self.args = args
        tp = json.load(open(TRACK))
        self.lanes = {ln: [tuple(p) for p in tp[ln]]
                      for ln in ("lane1", "lane2")}
        self.spacing = tp["meta"]["spacing_m"]

        latched = QoSProfile(reliability=QoSReliabilityPolicy.RELIABLE,
                             history=QoSHistoryPolicy.KEEP_LAST,
                             durability=QoSDurabilityPolicy.TRANSIENT_LOCAL,
                             depth=1)
        self.instr_pub = self.create_publisher(String, "/vla/instruction",
                                               latched)
        self.hold_pub = self.create_publisher(String, "/vla/hold", 5)
        self.floor_pub = self.create_publisher(String, "/vla/speed_floor", 5)
        qos = QoSProfile(reliability=QoSReliabilityPolicy.BEST_EFFORT,
                         history=QoSHistoryPolicy.KEEP_LAST,
                         durability=QoSDurabilityPolicy.VOLATILE, depth=5)
        self.create_subscription(TFMessage,
                                 "/world/default/dynamic_pose/info",
                                 self._tf_cb, qos)
        self.create_subscription(String, "/vla/instruction",
                                 self._instr_cb, latched)
        self.pose = None            # (x, y) proximity-tracked
        self.task = ""
        self.phase = "approach"
        self.ob_locked = None       # obstacle fixed at HOLD; survives the
                                    # lane swap (else _obstacle() would look
                                    # on the NEW lane and return None)
        self._still_t = None
        self._prev = None
        # a previous run may have left the bridge held — clear it
        self.create_timer(0.5, self._boot_release, )
        self.create_timer(0.1, self._tick)
        self.get_logger().info("avoid supervisor up — discrete decisions "
                               "here, driving and narration in the VLA")

    def _boot_release(self):
        if self.phase == "approach":
            self._hold(False)

    # ------------------------------------------------------------ inputs

    def _tf_cb(self, msg):
        # proximity tracking seeded at the demo's known start pose — the
        # same scheme the recorder uses against dynamic_pose index shifts
        ref = self.pose or (self.args.seed_x, self.args.seed_y)
        best = None
        for t in msg.transforms:
            x = t.transform.translation.x
            y = t.transform.translation.y
            d = math.hypot(x - ref[0], y - ref[1])
            if best is None or d < best[0]:
                best = (d, x, y)
        if best and best[0] < 3.0:
            self.pose = (best[1], best[2])

    def _instr_cb(self, msg):
        t = msg.data.strip()
        if t and t != self.task and self.phase == "approach":
            self.task = t

    def _registry_xy(self):
        try:
            return [(e["x"], e["y"]) for e in json.load(open(REGISTRY))]
        except Exception:
            return []

    def _obstacle(self):
        """Nearest registry car that sits in the ego's instructed lane."""
        low = self.task.lower()
        lane = "lane1" if ("inner" in low or "left" in low) else "lane2"
        try:
            entries = json.load(open(REGISTRY))
        except Exception:
            return None, lane
        for e in entries:
            if e.get("lane") == lane:
                pts = self.lanes[lane]
                i = min(range(len(pts)),
                        key=lambda j: (pts[j][0] - e["x"]) ** 2
                        + (pts[j][1] - e["y"]) ** 2)
                return {"x": e["x"], "y": e["y"], "index": i,
                        "lane": lane}, lane
        return None, lane

    def _lane_of(self, x, y):
        d1 = min((px-x)**2+(py-y)**2 for px, py in self.lanes["lane1"][::3])
        d2 = min((px-x)**2+(py-y)**2 for px, py in self.lanes["lane2"][::3])
        return "lane1" if d1 < d2 else "lane2"

    def _arc_fwd(self, ob):
        pts = self.lanes[ob["lane"]]
        n = len(pts)
        ex, ey = self.pose
        ei = min(range(n), key=lambda j: (pts[j][0] - ex) ** 2
                 + (pts[j][1] - ey) ** 2)
        loop = n * self.spacing
        fwd = ((ob["index"] - ei) % n) * self.spacing
        return fwd - loop if fwd > loop / 2.0 else fwd

    # ------------------------------------------------------------- logic

    def _hold(self, on):
        self.hold_pub.publish(String(data="on" if on else "off"))

    def _tick(self):
        if not self.task or self.pose is None:
            return
        if self.ob_locked is not None:
            ob, lane = self.ob_locked
        else:
            ob, lane = self._obstacle()
        if ob is None:
            return
        fwd = self._arc_fwd(ob)
        now = time.monotonic()

        if self.phase == "approach" and 0.0 < fwd <= self.args.hold_at:
            self._hold(True)
            self.phase, self._still_t = "hold", None
            self.ob_locked = (ob, lane)
            self.get_logger().info(
                f"HOLD — car {fwd:.1f} m ahead in {lane}; watching")
        elif self.phase == "hold":
            self._hold(True)               # keep asserting
            if self._prev and math.hypot(self.pose[0] - self._prev[0],
                                         self.pose[1] - self._prev[1]) < 0.03:
                self._still_t = self._still_t or now
            if self._still_t and now - self._still_t >= self.args.watch_s:
                other = "lane1" if lane == "lane2" else "lane2"
                sent = (f"Cruise in the {LANE_SENT[other]} lane, "
                        "at a normal speed.")
                self.task = sent
                self.instr_pub.publish(String(data=sent))
                self._hold(False)
                self.phase = "pass"
                self._floor_on = False
                self.get_logger().info(
                    f"GO — watched {self.args.watch_s:.1f}s, passing via "
                    f"{other}")
        elif self.phase == "pass" and not getattr(self, "_floor_on", False) \
                and self._lane_of(*self.pose) != ob["lane"]:
            # crossed onto the passing lane: now floor the speed so the
            # stop-near-car reflex cannot stall the overtake
            self.floor_pub.publish(String(data=str(self.args.pass_floor)))
            self._floor_on = True
            self.get_logger().info("crossed — pass floor on")
        elif self.phase == "pass" and 0.0 < fwd < 6.5 and \
                self._lane_of(*self.pose) == ob["lane"]:
            # head-on only: once the ego is on the other lane, a small fwd
            # means passing BESIDE the car, which is the whole point
            # safety net: still closing head-on on the blocked lane —
            # re-assert the hold rather than let the pass become a contact
            self._hold(True)
            self.phase, self._still_t = "hold", None
            self.get_logger().warn(
                f"re-HOLD — pass not clearing, car {fwd:.1f} m ahead")
        elif self.phase == "pass" and fwd < 0 and -fwd >= self.args.clear_m:
            self.phase = "done"
            self.floor_pub.publish(String(data="0"))
            self.get_logger().info("cleared — pass complete")
        self._prev = self.pose


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hold-at", type=float, default=14.0,
                    help="arc distance (m, center) to assert the hold")
    ap.add_argument("--watch-s", type=float, default=2.5)
    ap.add_argument("--clear-m", type=float, default=6.0)
    ap.add_argument("--pass-floor", type=float, default=1.2,
                    help="min speed (m/s) enforced during the pass so the "
                        "policy's stop-near-car reflex cannot stall it")
    ap.add_argument("--seed-x", type=float, required=True,
                    help="ego start x (proximity-tracking seed)")
    ap.add_argument("--seed-y", type=float, required=True)
    args = ap.parse_args()
    rclpy.init()
    node = AvoidSupervisor(args)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()
    return 0


if __name__ == "__main__":
    sys.exit(main())
